---
- hosts: workstation

  tasks:
    - include_vars: ../../vars/keys.enc.yml
    - include_vars: ../../vars/aws.yml

    - name: Make sure target is present
      file: dest=~/.target state=directory
      sudo: false 

    - name: Download aws client bundle
      get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=~/.target/awscli-bundle.zip
      sudo: false
      
    - name: Extract aws client bundle
      unarchive: src=~/.target/awscli-bundle.zip dest=~/.target creates=~/.target/awscli-bundler/install
      sudo: false

    - name: install aws cli
      shell: ~/.target/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws creates=/usr/local/bin/aws
      sudo: false 

    - name: Create aws directory
      file: dest=~/.aws state=directory
      sudo: false

    - name: Create aws credentials configuration file
      template: src=aws/credentials.j2 dest=~/.aws/credentials
      sudo: false

    - name: Create aws configuration file
      template: src=aws/config.j2 dest=~/.aws/config
      sudo: false
