.prepare:
	curl -sL https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/virtualenv-burrito.sh | $SHELL

default:
	battle --ask-sudo-pass --config-file=`pwd`/config.yml --config-dir=`pwd` --verbose
